### ISSUE TITLE
There was an I/O error while executing a REST request: null at shutdown

### ISSUE THREAD

**Issue by andrewkm** [DiscordSRV/DiscordSRV#1466]
### Expected behavior

No shutdown errors.

### Actual behavior

https://github.com/DiscordSRV/DiscordSRV/issues/1280 has not been fixed.
Now the error on shutdown is larger.
https://pastebin.com/raw/ti5gqRf5

### Steps to reproduce

Stop server.

### Server software and version

Paper 1.19.2 Build 162

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by andrewkm** [comment]
@Vankka this continues to occur a year later using DiscordSRV dev branch compiled against https://github.com/DiscordSRV/DiscordSRV/commit/d4b27cccfe4318f7a8b887ee3adcd478c583e305 as well as Paper version 1.20.6-147-ver/1.20.6@e41d44f

**Comment by granny** [comment]
Should be fixed with the latest snapshot build. https://snapshot.discordsrv.com

**Comment by Vankka** [comment]
The massive JDAAppender error has been rectified but the smaller errors still persist https://github.com/DiscordSRV/DiscordSRV/issues/1280
