### ISSUE TITLE
UltimateChat hook Not working

### ISSUE THREAD

**Issue by luiswenner** [DiscordSRV/DiscordSRV#814]
currently the plugin is not hooking with the ultimate chat plugin, this causes problems when messages are sent from the discord channel and are not displayed in-game.
steps to reproduce:
use latest paper version, latest ultimatechat version, latest version discordsrv version.
1- send a message on the discord channel
2- XXX message is not displayed in-game (however, it is displayed on the console)
I performed the tests without the ultimatechat plugin, and it worked perfectly!
`[12:50:38 INFO]: [DiscordSRV] [DEBUG] No UltimateFancy class found to use for UltimateChat hook`
[Debug Link](https://bin.scarsz.me/223015d7-93c8-4431-9e24-fa372cc2b22e#FRYG0nVF05BU6ntqdxAOaNNRFzpEYjOI)

**Comment by Vankka** [comment]
Fixed. https://github.com/DiscordSRV/DiscordSRV/commit/78f294ea5bdaa7e248ef3f1dccd18fa254e55f60

**Comment by luiswenner** [comment]
the problem persists in the last devbuild, I tested it but the problem is different now, but it still doesn't work
`[23:29:27 INFO]: [DiscordSRV] [DEBUG] No UltimateFancy constructor found to use for UltimateChat hook`

[Debug Link](https://bin.scarsz.me/3efc61b2-0adc-49ea-b16c-20298d2796a7#zb1kbLZAc2TYZTkUOqkgDiNrxXKXWYd0)

**Comment by luiswenner** [comment]
solved in [b7a7eec](https://github.com/DiscordSRV/DiscordSRV/commit/b7a7eec0fabdb83900e13c635ab8d7add98870a7)
